defmodule Cesizen.Repo.Migrations.AddEmailUniqueFieldToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :name, :citext
      add :email, :citext, null: false
    end

    create unique_index(:users, [:email], name: "users_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    alter table(:users) do
      remove :email
      modify :name, :text
    end
  end
end
