defmodule Cesizen.Repo.Migrations.CreateUserEmotionsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_emotions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_emotions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :emotion_id,
          references(:emotions,
            column: :id,
            name: "user_emotions_emotion_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_emotions, "user_emotions_user_id_fkey")

    drop constraint(:user_emotions, "user_emotions_emotion_id_fkey")

    drop table(:user_emotions)
  end
end
