defmodule Cesizen.Repo.Migrations.AddPasswordAuthenticationForUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:email], name: "users_email_index")

    alter table(:users) do
      remove :confirmed_at
      remove :hashed_password
    end
  end
end
