#!/bin/sh

echo

if [ ! -d "deps" ] || [ ! "$(ls -A deps)" ]; then
    printf "\e[32m=> Fetching dependencies and building the application...\e[0m\n\n"
    echo "+ mix do deps.get, compile --verbose"
    mix do deps.get, compile --verbose
    echo
fi

if [ ! -d "$PGDATA" ]; then
    printf "\e[32m=> Initialising the database in $PGDATA...\e[0m\n\n"
    echo "+ initdb --no-locale --encoding=UTF-8"
    initdb --no-locale --encoding=UTF-8
    echo
fi

if [ ! -f "$PGDATA/postmaster.pid" ]; then
    printf "\e[32m=> Starting PostgreSQL...\e[0m\n\n"
    echo "+ pg_ctl -o \"-k $PGDATA\" -l \"$PGDATA/server.log\" start"
    pg_ctl -o "-k \"$PGDATA\"" -l "$PGDATA/server.log" start
    echo
fi

printf "\e[32m=> Creating the postgres user if necessary...\e[0m\n\n"
echo "+ createuser --host $PGDATA postgres --createdb --echo"
createuser --host "$PGDATA" postgres --createdb --echo
echo

printf "\e[32m=> Compiles the application and run backend tests...\e[0m\n\n"
echo "+ mix test"
mix test
echo
