[package]
name = "cesizen-api"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
